export const INCREMENT = 'INCREMENT' ; 
export const DECREMENT = 'DECREMENT' ; 
export const RESET = 'RESET' ;

export const  GET_PRODUCTS_LOADING = "GET_PRODUCTS_LOADING";
export const  GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const  GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";

export const  ADD_PRODUCT_BASKET = "ADD_PRODUCT_BASKET";
export const  UPDATE_PRODUCT_BASKET = "UPDATE_PRODUCT_BASKET";
export const  DECREMENT_PRODUCT_BASKET = "DECREMENT_PRODUCT_BASKET";
export const  REMOVE_PRODUCT_BASKET = "REMOVE_PRODUCT_BASKET";